format = "$time $directory $git_branch $fill $cmd_duration $line_break $character"

add_newline = false

[directory]
style = 'fg:blue'
format = '[$path]($style)'
truncation_length = 3
truncation_symbol = 'â€¦/'
truncate_to_repo = false

[git_branch]
style = 'fg:green'
format = '[\[$branch\]]($style) '

[fill]
symbol = ' '

[cmd_duration]
min_time = 500
style = 'fg:gray'
format = '[$duration]($style)'

[time]
disabled = false
format = '[$time]($style) '
time_format = '%H:%M:%S%.3f'

