console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 4
final_space = true

[palette]
  black = '#262B44'
  blue = '#4B95E9'
  green = '#59C9A5'
  orange = '#F07623'
  red = '#D81E5B'
  white = '#E0DEF4'
  yellow = '#F3AE35'

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'status'
    template = ' {{ if gt .Code 0 }}{{ else }}{{ end }}'
    foreground = 'p:green'
    foreground_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']

    [blocks.segments.options]
      always_enabled = true

  [[blocks.segments]]
    type = 'time'
    template = ' {{ .CurrentDate | date "15:04:05.000" }}'
    foreground = 'p:blue'

  [[blocks.segments]]
    type = 'path'
    template = ' {{ path .Path .Location }}'
    foreground = 'p:orange'

    [blocks.segments.options]
      style = "full"

  [[blocks.segments]]
    type = 'git'
    template = ' [{{ .HEAD }}]'
    foreground = 'p:green'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}', '{{ if gt .Ahead 0 }}#49416D{{ end }}', '{{ if gt .Behind 0 }}#7A306C{{ end }}']

    [blocks.segments.options]
      fetch_status = true
      fetch_upstream_icon = true
      branch_icon = ''
